### ISSUE TITLE
Make commands configurable

### ISSUE THREAD

**Issue by allejo** [macsforme/mutedChatHelper#1]
What are your thoughts on making this configurable through a separate text file? Define a syntax for each line to message pairing.

https://github.com/macsforme/mutedChatHelper/blob/8db191c310f927fe7a8940c03830544375ca1759/mutedChatHelper.cpp#L80-L100

The API has [`getFileTextLines()`](https://github.com/BZFlag-Dev/bzflag/blob/2.4/plugins/plugin_utils/plugin_files.h#L41) in `plugin_files.h`.

For example, something like:

```
hi {player}; Hello, {player}
ours; Ours!
icanoffi; I can play an official match
icanoffi {15,20,30}; I can play a {duration}-minute match
```

**Comment by macsforme** [comment]
I think this would be ideal. However, given the anticipated limited use of this plugin, I question whether there would be any practical benefit to justify the additional effort and complication. What else do you see this plugin being used for that could justify implementing this?

**Comment by allejo** [comment]
I had originally envisioned this being usable on a family friendly server but I'm having troubles thinking of practical uses for unregistered players on family friendly servers so that idea may be moot.

**Comment by macsforme** [comment]
While I'm in favor of future-proofing code, I feel this extra configurability may be premature given the current intended purpose of this plugin. Closing for now, but if the use of this plugin is expanded at a later time, this idea can be revisited.
